# We are (unfortunately) dealing with a C++ project.
language: cpp
compiler: gcc

# Use Ubuntu 14.04.5 LTS (Trusty Tahr) instead of Ubuntu 12.04.5 LTS (Precise Pangolin)
dist: trusty

cache:
    directories:
        # Cache the boost install
        - $HOME/boost_1_61_0/boost
        - $HOME/boost_1_61_0/stage/lib

# We're going to need cmake and boost.
addons:
    sources:
        - ubuntu-toolchain-r-test
    apt:
        packages:
            - gcc-5
            - g++-5
            - cmake
            # Don't grab the APT boost package, because that package is stale.
            # We'll need to build boost ourselves.
            # - libboost-all-dev

before_install:
    # Print the CMake version.
    - cmake --version
    # Build and install boost
    - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.0.0/install_boost.py
    - python install_boost.py --directory ~ --boost-version 1.61.0 atomic chrono date_time filesystem iostreams locale log regex system thread
    # Set the BOOST_ROOT variable
    - export BOOST_ROOT=$HOME/boost_1_61_0/boost

script:
    - make all
    - make test