# We are (unfortunately) dealing with a C++ project.
language: cpp
compiler: gcc

# Use Ubuntu 14.04.5 LTS (Trusty Tahr) instead of Ubuntu 12.04.5 LTS (Precise Pangolin)
dist: trusty

cache:
    directories:
        # Cache the boost install
        - $HOME/boost_1_61_0/boost
        - $HOME/boost_1_61_0/stage/lib

# We're going to need cmake and boost.
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - cmake
            # Don't grab the APT boost package, because that package is stale.
            # We'll need to build boost ourselves.
            # - libboost-all-dev

before_install:
    # Use GCC 5.
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    # Print the CMake version.
    - cmake --version
    # Build and install boost
    - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.0.0/install_boost.py
    - python install_boost.py --directory ~ --boost-version 1.61.0 atomic chrono date_time filesystem iostreams locale log regex system thread

script:
    # make configure
    - cmake -E make_directory ./build
    - cmake -E chdir ./build cmake -DCMAKE_GENERATOR="Unix Makefiles" -DBOOST_ROOT=$HOME/boost_1_61_0 ../src
    # make all
    - make -j -C ./build all
    # make install_main
    - make -j -C ./build/main --no-print-directory install
    # make install_test
    - make -j -C ./build/test --no-print-directory install
    # make test
    - make -C ./build/test --no-print-directory run_ctest
