# We are (unfortunately) dealing with a C++ project.
language: cpp
# Test with both clang and gcc, because why not?
compiler:
    - clang
    - gcc

# We're going to need cmake and boost.
addons:
    apt:
        packages:
        - cmake
        - libboost-all-dev

before_install:
    # Print the CMake version.
    - cmake --version

script:
    # Make the project and run the tests.
    - make all
    - make test