# This .travis.yml is based on LOOT's .travis.yml:
# https://github.com/loot/loot/blob/dev/.travis.yml
 

# We are (unfortunately) dealing with a C++ project.
language: cpp

# Use Ubuntu 14.04.5 LTS (Trusty Tahr) instead of Ubuntu 12.04.5 LTS (Precise Pangolin)
dist: trusty

cache:
  directories:
    # Cache the boost install
    - $HOME/boost_1_63_0/boost
    - $HOME/boost_1_63_0/stage/lib
    - $HOME/poco

# We're going to need MPI and the mono runtime.
addons:
  apt:
    packages: &default_packages
      - mono-runtime
      - libmono-corlib2.0-cil
      - libmono-corlib4.0-cil
      - libmono-corlib4.5-cil
      - libmono-system-xml4.0-cil
      - libmono-system-core4.0-cil
      - mpich
      - libmpich-dev
      # The CMake package is kind of dated. We'll download a later version
      # of cmake later on.
      # - cmake
      # Don't grab the APT boost package, because that package is stale.
      # We'll need to build boost ourselves.
      # - libboost-all-dev
      # The hdf5 package is also outdated. We will install 1.8.16    
      # - libhdf5-serial-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIG_IDENTIFIER='linux-gcc-6' CC_COMPILER_NAME='gcc-6' CXX_COMPILER_NAME='g++-6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - mono
          packages:
            - *default_packages
            - gcc-6
            - g++-6

    - os: linux
      compiler: clang
      env: CONFIG_IDENTIFIER='linux-clang-4.0-tbb' CC_COMPILER_NAME='clang-4.0' CXX_COMPILER_NAME='clang++-4.0'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
            - mono
          packages:
            - *default_packages
            - clang-4.0
            - clang++-4.0
            - libstdc++-6-dev
            - libtbb-dev

    - os: linux
      compiler: clang
      env: CONFIG_IDENTIFIER='linux-clang-4.0' CC_COMPILER_NAME='clang-4.0' CXX_COMPILER_NAME='clang++-4.0'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
            - mono
          packages:
            - *default_packages
            - clang-4.0
            - clang++-4.0
            - libstdc++-6-dev

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CONFIG_IDENTIFIER='osx-clang' CC_COMPILER_NAME='clang' CXX_COMPILER_NAME='clang++'

before_install:
  # If we're working with an OS X machine, then want to install homebrew packages (the APT packages
  # will be ignored)
  - if [ $TRAVIS_OS_NAME == "osx" ]; then brew update; brew install mono; brew install gcc; brew install mpich; brew install wget; fi
  - export CXX="$CXX_COMPILER_NAME" CC="$CC_COMPILER_NAME"
  # Print the C++ compiler version.
  - $CXX --version
  # Print the Mono version number.
  - mono --version
  # Grab a relatively recent version of CMake, unzip it and add
  # it to the path.
  - if [ $TRAVIS_OS_NAME != "osx" ]; then wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz; tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz; export PATH="$PWD/cmake-3.8.0-Linux-x86_64/bin/:$PATH"; fi
  # Print the CMake version.
  - cmake --version
  # Grab the gtest report pretty printer.
  - wget https://github.com/jonathanvdc/gtest-report-tools/releases/download/v0.1.3/gtest-report-tools.zip
  - unzip gtest-report-tools.zip -d gtest-report-tools
  # Build and install boost.
  - echo "using mpi ;" > ~/site-config.jam
  - wget https://raw.githubusercontent.com/flu-plus-plus/ci-scripts/master/install_boost.py
  - python install_boost.py --directory ~ --boost-version 1.63.0 --address-model 64 --toolchain=$CC_COMPILER_NAME --stagedir stage atomic chrono date_time filesystem iostreams locale log regex system thread serialization mpi
  # Set the BOOST_ROOT environment variable.
  - export BOOST_ROOT=$HOME/boost_1_63_0
  - if [ $TRAVIS_OS_NAME == "osx" ]; then sudo cp $HOME/boost_1_63_0/stage/lib/* /usr/local/lib/; else export LD_LIBRARY_PATH=$HOME/boost_1_63_0/stage/lib:$LD_LIBRARY_PATH; fi
  
  # Build and install Poco
  - if [ $TRAVIS_OS_NAME != "osx" ]; then mkdir -p $HOME/poco; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then wget https://pocoproject.org/releases/poco-1.7.8/poco-1.7.8p2.tar.gz; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then tar -xzf poco-1.7.8p2.tar.gz -C $HOME/poco; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then pushd $HOME/poco/poco-1.7.8p2; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then ./configure; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then make -s; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then sudo make -s install; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then popd; fi
  
  # Build and install HDF5 v1.8.16
  - mkdir -p $HOME/soft
  - pushd $HOME/soft
  - export HDF5_VER_MAJOR=18
  - export HDF5_VER_MINOR=1.8.16
  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-$HDF5_VER_MINOR.tar.gz
  - tar -zxvf hdf5-$HDF5_VER_MINOR.tar.gz
  - cd hdf5-$HDF5_VER_MINOR
  - ./configure --prefix=$HOME/usr --libdir=$HOME/usr/lib$CLUSTER --bindir=$HOME/usr/bin$CLUSTER
  - make install
  - popd


script:
  # `make all; make test`, but fancier.
  - make all
  - make test_all
  # Push the report to our website.
  - ./push-report.sh
  # Pretty-print the test results.
  - mono gtest-report-tools/gtest-report-print.exe --ansi build/installed/bin/gtester_all.xml
