# This .travis.yml is based on LOOT's .travis.yml:
# https://github.com/loot/loot/blob/dev/.travis.yml
 

# We are (unfortunately) dealing with a C++ project.
language: cpp
compiler: gcc

# Use Ubuntu 14.04.5 LTS (Trusty Tahr) instead of Ubuntu 12.04.5 LTS (Precise Pangolin)
dist: trusty

cache:
    directories:
        # Cache the boost install
        - $HOME/boost_1_61_0/boost
        - $HOME/boost_1_61_0/stage/lib

# We're going to need cmake and boost.
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - cmake
            - mpich
            - libmpich-dev
            - libsdl1.2-dev
            # Don't grab the APT boost package, because that package is stale.
            # We'll need to build boost ourselves.
            # - libboost-all-dev

before_install:
    # Use GCC 5.
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    # Print the CMake version.
    - cmake --version
    # Build and install boost.
    - echo "using mpi ;" > ~/site-config.jam
    - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.0.0/install_boost.py
    - python install_boost.py --directory ~ --boost-version 1.61.0 atomic chrono date_time filesystem iostreams locale log regex system thread serialization mpi
    # Set the BOOST_ROOT environment variable.
    - export BOOST_ROOT=$HOME/boost_1_61_0
    - export LD_LIBRARY_PATH=$HOME/boost_1_61_0/stage/lib:$LD_LIBRARY_PATH
    
    # Download, build and install Awesomium and its dependencies
    - wget -O libgcrypt.deb http://security.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.0-3ubuntu0.6_amd64.deb
    - sudo dpkg -i libgcrypt.deb    
    
    - wget -O libudev.deb http://mirrors.kernel.org/ubuntu/pool/main/u/udev/libudev0_175-0ubuntu9_amd64.deb
    - sudo dpkg -i libudev.deb
    
    - wget -O awesomium.tar.gz http://www.awesomium.com/downloads/awesomium_1_7_5_sdk_linux64.tar.gz
    - tar -xvzf awesomium.tar.gz 
    - sudo make -C awesomium_v1.7.5_sdk_linux64 install

script:
    # `make all; make test`, as per the build instructions.
    - make all
    # Don't make tests that rely on X to work/render things.
    - make test_all_no_x
